
name: Deploy Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # if your docs needs submodules, uncomment the following line
          # submodules: true
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install Deps
        run: npm ci

      - name: Build Docs
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: npm run docs:build

      - name: create-archive
        run: tar czf docs.tar.gz -C ./src/.vuepress/dist/ .
        
      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "docs.tar.gz"
          target: /etc/nginx/sites-available

      - name: ssh
        uses: appleboy/ssh-action@v1.0.3
        env:
          SHA: ${{ github.sha }}
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            port: ${{ secrets.PORT }}
            script: |
              cd /etc/nginx/sites-available/ 
              mv docs "docs_backup_$(date '+%Y_%m_%d_%H_%M')"
              mkdir docs
              tar -xzvf docs.tar.gz -C /etc/nginx/sites-available/docs
              mv docs.tar.gz docs_release_$(date '+%Y_%m_%d_%H_%M')_tar.gz
              
